# Choose a backend by uncommenting one block and commenting out the others.

# Railway
#backendBaseUrl=https://machi-koro.up.railway.app
#websocketUrl=wss://machi-koro.up.railway.app/ws

# Render
backendBaseUrl=https://machi-koro-server.onrender.com
websocketUrl=wss://machi-koro-server.onrender.com/ws

# Uni server
#backendBaseUrl=http://se2-demo.aau.at:53210
#websocketUrl=ws://se2-demo.aau.at:53210/ws