sonar.projectKey=SE2-Machi-Koro_Client
sonar.organization=se2-machi-koro
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.sourceEncoding=UTF-8

sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
sonar.qualitygate.wait=true

# Exclusions - UI and Resource files
sonar.exclusions=**/build/**,**/generated/**,**/gradlew**,**/ui/**,**/res/**,**/AndroidManifest.xml,**/*.xml
sonar.test.exclusions=**/build/**,**/androidTest/**
sonar.coverage.exclusions=**/build/**,**/generated/**,**/ui/**,**/res/**